### ISSUE TITLE
Error when running npx create-nuxt-app and npm init nuxt-app

### ISSUE THREAD

**Issue by ymekuria** [nuxt/create-nuxt-app#1017]
### Version
create-nuxt-app v5.0.0

### Steps to reproduce
I went through the CLI with the below options
```
? Project name: nuxttest
? Programming language: TypeScript
? Package manager: Npm
? UI framework: None
? Template engine: HTML
? Nuxt.js modules: Axios - Promise based HTTP client
? Linting tools: Prettier
? Testing framework: None
? Rendering mode: Single Page App
? Deployment target: Server (Node.js hosting)
? Development tools: jsconfig.json (Recommended for VS Code if you're not using typescript)
? Continuous integration: None
? Version control system: None
```

### What is Expected?
The project to open to the template landing page when `npm run dev is entered`

### What is actually happening?
after runing `npm run dev` I get the below error and stack trace

```
> nuxttest@1.0.0 dev
> nuxt


 WARN  Module @nuxt/telemetry not found.                                                                                                       02:39:31


 FATAL  Cannot find module '/node_modules/@nuxt/telemetry/dist/index.js'. Please verify that the package.json has a valid "main" entry

  at tryPackage (node:internal/modules/cjs/loader:354:19)
  at Module._findPath (node:internal/modules/cjs/loader:567:18)
  at Module._resolveFilename (node:internal/modules/cjs/loader:925:27)
  at Function.resolve (node:internal/modules/cjs/helpers:108:19)
  at _resolve (node_modules/jiti/dist/jiti.js:1:243302)
  at Resolver.jiti [as _require] (node_modules/jiti/dist/jiti.js:1:245428)
  at Resolver.requireModule (node_modules/@nuxt/core/dist/core.js:381:29)
  at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:182:38)
  at node_modules/@nuxt/utils/dist/utils.js:639:43
  at async ModuleContainer.ready (node_modules/@nuxt/core/dist/core.js:58:5)
  at async Nuxt._init (node_modules/@nuxt/core/dist/core.js:478:5)
```
                                                                                                                        
```
      ✖ Nuxt Fatal Error                                                                                                     

     '/node_modules/@nuxt/telemetry/dist/index.js'.   
     Please verify that the package.json has a valid "main" entry        
```

**Comment by ymekuria** [comment]
I reproduced the same error using `npm init nuxt-app` as well.
