### ISSUE TITLE
Dev server issue

### ISSUE THREAD

**Issue by rwxmad** [nuxt/create-nuxt-app#1020]
![Снимок экрана 2022-11-25 в 07 47 13](https://user-images.githubusercontent.com/30772868/203903436-2f78cca1-6e1d-4628-807e-03c939093f61.png)

### Version
create-nuxt-app: 5.0.0
npm: 9.1.2
node: 19.1.0

**Comment by PiloeGAO** [comment]
Hello,

I can confirm the bug both in dev et production.

To reproduce, create a new project with the following settings:

```
create-nuxt-app v5.0.0
✨  Generating Nuxt.js project in demo
? Project name: demo
? Programming language: JavaScript
? Package manager: Yarn
? UI framework: None
? Template engine: HTML
? Nuxt.js modules: (Press <space> to select, <a> to toggle all, <i> to invert selection)
? Linting tools: ESLint, Prettier
? Testing framework: Jest
? Rendering mode: Universal (SSR / SSG)
? Deployment target: Server (Node.js hosting)
? Development tools: jsconfig.json (Recommended for VS Code if you're not using typescript)
? Continuous integration: None
? Version control system: Git
warning nuxt > @nuxt/babel-preset-app > core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage
warning nuxt > @nuxt/babel-preset-app > core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage
 due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdow
n up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to
warning nuxt > @nuxt/babel-preset-app > core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage
 due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdow
n up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to
warning nuxt > @nuxt/babel-preset-app > core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage
 due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdow
n up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to
 the actual version of core-js.
warning nuxt > @nuxt/webpack > terser-webpack-plugin > cacache > @npmcli/move-file@1.1.2: This functionality has been moved t
o @npmcli/fs
warning nuxt > @nuxt/webpack > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 does not receive securi
warning nuxt > @nuxt/babel-preset-app > core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage
 due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdow
n up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to
 the actual version of core-js.
warning nuxt > @nuxt/webpack > terser-webpack-plugin > cacache > @npmcli/move-file@1.1.2: This functionality has been moved t
o @npmcli/fs
warning nuxt > @nuxt/webpack > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 does not receive securi
ty updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
warning nuxt > @nuxt/webpack > webpack > watchpack > watchpack-chokidar2 > chokidar > fsevents@1.2.13: fsevents 1 will break
on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning nuxt > @nuxt/webpack > postcss-preset-env > postcss-color-gray > postcss-values-parser > flatten@1.0.3: flatten is de
precated in favor of utility frameworks such as lodash.
warning nuxt > @nuxt/babel-preset-app > core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage
 due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdow
n up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to
 the actual version of core-js.
warning nuxt > @nuxt/webpack > terser-webpack-plugin > cacache > @npmcli/move-file@1.1.2: This functionality has been moved t
o @npmcli/fs
warning nuxt > @nuxt/webpack > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 does not receive securi
ty updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
warning nuxt > @nuxt/webpack > webpack > watchpack > watchpack-chokidar2 > chokidar > fsevents@1.2.13: fsevents 1 will break
on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning nuxt > @nuxt/webpack > postcss-preset-env > postcss-color-gray > postcss-values-parser > flatten@1.0.3: flatten is de
precated in favor of utility frameworks such as lodash.
warning nuxt > @nuxt/babel-preset-app > core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage
 due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdow
n up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to
 the actual version of core-js.
warning nuxt > @nuxt/webpack > terser-webpack-plugin > cacache > @npmcli/move-file@1.1.2: This functionality has been moved t
o @npmcli/fs
warning nuxt > @nuxt/webpack > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 does not receive securi
ty updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
warning nuxt > @nuxt/webpack > webpack > watchpack > watchpack-chokidar2 > chokidar > fsevents@1.2.13: fsevents 1 will break
on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning nuxt > @nuxt/webpack > postcss-preset-env > postcss-color-gray > postcss-values-parser > flatten@1.0.3: flatten is de
precated in favor of utility frameworks such as lodash.
warning nuxt > @nuxt/webpack > cssnano > cssnano-preset-default > postcss-svgo > svgo@1.3.2: This SVGO version is no longer s
warning nuxt > @nuxt/babel-preset-app > core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage
 due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdow
n up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to
 the actual version of core-js.
warning nuxt > @nuxt/webpack > terser-webpack-plugin > cacache > @npmcli/move-file@1.1.2: This functionality has been moved t
o @npmcli/fs
warning nuxt > @nuxt/webpack > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 does not receive securi
ty updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
warning nuxt > @nuxt/webpack > webpack > watchpack > watchpack-chokidar2 > chokidar > fsevents@1.2.13: fsevents 1 will break
on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
warning nuxt > @nuxt/webpack > postcss-preset-env > postcss-color-gray > postcss-values-parser > flatten@1.0.3: flatten is de
precated in favor of utility frameworks such as lodash.
warning nuxt > @nuxt/webpack > cssnano > cssnano-preset-default > postcss-svgo > svgo@1.3.2: This SVGO version is no longer s
upported. Upgrade to v2.x.x.
warning nuxt > @nuxt/webpack > webpack > micromatch > snapdragon > source-map-resolve@0.5.3: See https://github.com/lydell/so
urce-map-resolve#deprecated
warning nuxt > @nuxt/webpack > webpack > node-libs-browser > url > querystring@0.2.0: The querystring API is considered Legac
y. new code should use the URLSearchParams API instead.
warning nuxt > @nuxt/webpack > cssnano > cssnano-preset-default > postcss-svgo > svgo > stable@0.1.8: Modern JS already guara
ntees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.moz
illa.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
warning nuxt > @nuxt/webpack > webpack > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com
/lydell/resolve-url#deprecated
warning nuxt > @nuxt/webpack > webpack > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github
.com/lydell/urix#deprecated
warning nuxt > @nuxt/webpack > webpack > micromatch > snapdragon > source-map-resolve > source-map-url@0.4.1: See https://git
hub.com/lydell/source-map-url#deprecated
warning vue-jest > babel-plugin-transform-es2015-modules-commonjs > babel-runtime > core-js@2.6.12: core-js@<3.23.3 is no lon
ger maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection i
n old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility
yarn run v1.22.19
$ prettier --write --list-different . && yarn lint:js --fix
.eslintrc.js
components\NuxtLogo.vue
components\Tutorial.vue
jest.config.js
nuxt.config.js
package.json
pages\index.vue
README.md
$ eslint --ext ".js,.vue" --ignore-path .gitignore . --fix
Done in 24.60s.

🎉  Successfully created project demo

  To get started:

        cd demo
        yarn dev

  To build & start for production:

        cd demo
        yarn build
        yarn start

  To test:

        cd demo
        yarn test

Done in 267.99s.
```

Nuxt Infos:
```
Nuxi 3.0.0                                                                                                                      20:21:11
                                                                                                                                20:21:11
RootDir: C:/DEV/NuxtTutorial/demo                                                                                               20:21:12
Nuxt project info:                                                                                                              20:21:12

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v18.12.1`
- Nuxt Version:     `2.15.8`
- Nitro Version:    `-`
- Package Manager:  `yarn@1.22.19`
- Builder:          `webpack`
- User Config:      `head`, `css`, `plugins`, `components`, `buildModules`, `modules`, `build`
- Runtime Modules:  `-`
- Build Modules:    `@nuxtjs/eslint-module@3.1.0`
------------------------------

👉 Report an issue: https://github.com/nuxt/nuxt.js/issues/new                                                                  20:21:12

👉 Suggest an improvement: https://github.com/nuxt/nuxt.js/discussions/new

👉 Read documentation: https://nuxtjs.org

```

After investigating, the server can be run by using the following environment variable (powershell): ```$env:NODE_OPTIONS="--openssl-legacy-provider"```
This works but it's a workaround and building a production project should be prohibited. 

Can somebody from the dev team look at it ?

Thank you in advance,
Have a nice day,
Leo D.

**Comment by M9lTHblu** [comment]
Environment variable workaround doesn't always work
<img width="1680" alt="Снимок экрана 2022-11-30 в 13 49 34" src="https://user-images.githubusercontent.com/51918498/204776963-3573a74a-1c93-45dd-9773-dd7acc42cc41.png">

**Comment by M9lTHblu** [comment]
Appreciate the mediocre support of Nuxt developers: https://github.com/nuxt/nuxt.js/issues/10779

**Comment by Pictor13** [comment]
https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported
https://itsmycode.com/error-digital-envelope-routines-unsupported/

Node version is not LTS and is not supported. Solution is to downgrade or specify legacy openssl version (see links).

**Comment by jonrandahl** [comment]
Same warnings and failure to run `yarn dev` while using nodejs LTS (v18.12.1):

```sh
[01/02/23] 22:09:52 ✝  ~/Projects/training  npx create-nuxt-app nuxt-init
Need to install the following packages:
  create-nuxt-app@5.0.0
Ok to proceed? (y) y
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated

create-nuxt-app v5.0.0
✨  Generating Nuxt.js project in nuxt-init
? Project name: nuxt-init
? Programming language: JavaScript
? Package manager: Yarn
? UI framework: None
? Template engine: HTML
? Nuxt.js modules: (Press <space> to select, <a> to toggle all, <i> to invert selection)
? Linting tools: ESLint, Prettier
? Testing framework: None
? Rendering mode: Single Page App
? Deployment target: Server (Node.js hosting)
? Development tools: jsconfig.json (Recommended for VS Code if you're not using typescript)
? Continuous integration: None
? Version control system: Git
warning nuxt > @nuxt/babel-preset-app > core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cau
se a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
warning nuxt > @nuxt/webpack > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
yarn run v1.22.19
$ prettier --write --list-different . && yarn lint:js --fix
.eslintrc.js
components/NuxtLogo.vue
components/Tutorial.vue
nuxt.config.js
package.json
pages/index.vue
README.md
$ eslint --ext ".js,.vue" --ignore-path .gitignore . --fix
✨  Done in 3.07s.

🎉  Successfully created project nuxt-init

  To get started:

	cd nuxt-init
	yarn dev

  To build & start for production:

	cd nuxt-init
	yarn build
	yarn start

npm notice
npm notice New major version of npm available! 8.19.2 -> 9.2.0
npm notice Changelog: https://github.com/npm/cli/releases/tag/v9.2.0
npm notice Run npm install -g npm@9.2.0 to update!
npm notice
[01/02/23] 23:50:09 ✝  ~/Projects/training  npm install -g npm@9.2.0

removed 14 packages, changed 75 packages, and audited 232 packages in 2s

14 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
Reshimming asdf nodejs...
[01/02/23] 23:50:32 ✝  ~/Projects/training  cd nuxt-init/
[01/02/23] 23:50:41 ✝  Projects/training/nuxt-init   develop±  yarn dev
yarn run v1.22.19
$ nuxt

   ╭───────────────────────────────────────╮
   │                                       │
   │   Nuxt @ v2.15.8                      │
   │                                       │
   │   ▸ Environment: development          │
   │   ▸ Rendering:   client-side          │
   │   ▸ Target:      server               │
   │                                       │
   │   Listening: http://localhost:3000/   │
   │                                       │
   ╰───────────────────────────────────────╯

ℹ Preparing project for development                                                                                                                                                                                                 23:50:49
ℹ Initial build may take a while                                                                                                                                                                                                    23:50:49
ℹ Discovered Components: .nuxt/components/readme.md                                                                                                                                                                                 23:50:49
✔ Builder initialized                                                                                                                                                                                                               23:50:49
✔ Nuxt files generated                                                                                                                                                                                                              23:50:49

● Client █████████████████████████ compiling (0%)


node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/jonhumphrey/Projects/training/nuxt-init/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/jonhumphrey/Projects/training/nuxt-init/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/jonhumphrey/Projects/training/nuxt-init/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/jonhumphrey/Projects/training/nuxt-init/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/jonhumphrey/Projects/training/nuxt-init/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/jonhumphrey/Projects/training/nuxt-init/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/jonhumphrey/Projects/training/nuxt-init/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/Users/jonhumphrey/Projects/training/nuxt-init/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/jonhumphrey/Projects/training/nuxt-init/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /Users/jonhumphrey/Projects/training/nuxt-init/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
    at /Users/jonhumphrey/Projects/training/nuxt-init/node_modules/graceful-fs/graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```
