### ISSUE TITLE
run yarn build and find error

### ISSUE THREAD

**Issue by bookyo** [nuxt/create-nuxt-app#127]
ERROR in ./node_modules/element-ui/lib/theme-chalk/index.css (./node_modules/css-loader??ref--3-oneOf-1-1!./node_modules/postcss-loader/src??ref--3-oneOf-1-2!./node_modules/element-ui/lib/theme-chalk/index.css)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: Cannot read property 'search' of undefined
    at /Volumes/data/www/topercms/node_modules/element-ui/lib/theme-chalk/index.css:1:145297
    at isValueCustomProp (/Volumes/data/www/topercms/node_modules/postcss-merge-longhand/dist/lib/decl/borders.js:106:45)
    at /Volumes/data/www/topercms/node_modules/postcss-merge-longhand/dist/lib/decl/borders.js:449:18
    at mergeRules (/Volumes/data/www/topercms/node_modules/postcss-merge-longhand/dist/lib/mergeRules.js:46:17)
    at wsc.forEach (/Volumes/data/www/topercms/node_modules/postcss-merge-longhand/dist/lib/decl/borders.js:438:34)
    at Array.forEach (<anonymous>)
    at Object.merge (/Volumes/data/www/topercms/node_modules/postcss-merge-longhand/dist/lib/decl/borders.js:436:9)
    at _decl2.default.forEach.p (/Volumes/data/www/topercms/node_modules/postcss-merge-longhand/dist/index.js:22:19)
    at Array.forEach (<anonymous>)
    at css.walkRules.rule (/Volumes/data/www/topercms/node_modules/postcss-merge-longhand/dist/index.js:20:28)
    at /Volumes/data/www/topercms/node_modules/postcss/lib/container.js:239:18
    at /Volumes/data/www/topercms/node_modules/postcss/lib/container.js:135:18
    at Root.each (/Volumes/data/www/topercms/node_modules/postcss/lib/container.js:101:16)
    at Root.walk (/Volumes/data/www/topercms/node_modules/postcss/lib/container.js:131:17)
    at Root.walkRules (/Volumes/data/www/topercms/node_modules/postcss/lib/container.js:237:19)
    at css (/Volumes/data/www/topercms/node_modules/postcss-merge-longhand/dist/index.js:19:13)
    at initializePlugin (/Volumes/data/www/topercms/node_modules/cssnano/dist/index.js:35:51)
 @ ./node_modules/element-ui/lib/theme-chalk/index.css 4:14-140
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js
✖ fatal Nuxt Build Error
Nuxt Fatal Error :(
error Command failed with exit code 1.
nuxt.config.js:
plugins: [
    '@/plugins/element-ui'
  ]
css: [
    'element-ui/lib/theme-chalk/index.css'
  ]

/plugins/element-ui:
import Vue from 'vue'
import Element from 'element-ui/lib/element-ui.common'
import locale from 'element-ui/lib/locale/lang/zh-CN'

export default () => {
  Vue.use(Element, { locale })
}

**Comment by gaconkzk** [comment]
Some addition information. 
- This error is happened when we using ElementUI with nuxt.
- This error happened when we run `yarn build` (it ok with `yarn dev`)

**Comment by solonik1** [comment]
Same issue

**Comment by solonik1** [comment]
Same issue

**Comment by zhebanzhongzhong** [comment]
找到解决方案了没有？

**Comment by aldarund** [comment]
it seems like issue with cssnano 
https://github.com/cssnano/cssnano/issues/644

**Comment by bookyo** [comment]
i resolve it by import the necessary css from element-ui.
like:
css: [
    'element-ui/lib/theme-chalk/base.css',
    'element-ui/lib/theme-chalk/icon.css',
    'element-ui/lib/theme-chalk/button.css',
    'element-ui/lib/theme-chalk/col.css',
    'element-ui/lib/theme-chalk/row.css',
    'element-ui/lib/theme-chalk/input.css',
    // 'element-ui/lib/theme-chalk/index.css',
    { src: '@/assets/css/main.css', lang: 'scss' },
    'swiper/dist/css/swiper.css',
    'video.js/dist/video-js.css'
  ],

**Comment by bookyo** [comment]
// nuxt.config.js
    build: {
        postcss: false,
        extend ..
    }
another way

**Comment by zhebanzhongzhong** [comment]
你用nuxt什么版本？2.0吗？

**Comment by aldarund** [comment]
Its bug in cssnano. Will be fixed in cssnano > v4.1.5
