### ISSUE TITLE
new project fails while yarn build/generate

### ISSUE THREAD

**Issue by dawnfantasy** [nuxt/create-nuxt-app#177]
How to reproduce:
npx create-nuxt-app  demo1
   framework: express
   render: universal
   rest: default

cd demo1
npm run build

ERROR in 92a8cf26fc2c7e65b970.js from Terser
TypeError: Cannot read property 'minify' of undefined
    at minify (/home/ubuntu/dev/demo1/node_modules/terser-webpack-plugin/dist/minify.js:175:23)
    at TaskRunner.boundWorkers (/home/ubuntu/dev/demo1/node_modules/terser-webpack-plugin/dist/TaskRunner.js:68:40)
    at enqueue (/home/ubuntu/dev/demo1/node_modules/terser-webpack-plugin/dist/TaskRunner.js:89:14)
    at tasks.forEach (/home/ubuntu/dev/demo1/node_modules/terser-webpack-plugin/dist/TaskRunner.js:109:9)
    at Array.forEach (<anonymous>)
    at TaskRunner.run (/home/ubuntu/dev/demo1/node_modules/terser-webpack-plugin/dist/TaskRunner.js:87:11)
    at TerserPlugin.optimizeFn (/home/ubuntu/dev/demo1/node_modules/terser-webpack-plugin/dist/index.js:224:18)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/ubuntu/dev/demo1/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:12:1)
    at AsyncSeriesHook.lazyCompileHook (/home/ubuntu/dev/demo1/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.additionalAssets.callAsync.err (/home/ubuntu/dev/demo1/node_modules/webpack/lib/Compilation.js:1311:36)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/ubuntu/dev/demo1/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (/home/ubuntu/dev/demo1/node_modules/tapable/lib/Hook.js:154:20)
    at hooks.optimizeTree.callAsync.err (/home/ubuntu/dev/demo1/node_modules/webpack/lib/Compilation.js:1307:32)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/home/ubuntu/dev/demo1/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:9:1)
    at AsyncSeriesHook.lazyCompileHook (/home/ubuntu/dev/demo1/node_modules/tapable/lib/Hook.js:154:20)
    at Compilation.seal (/home/ubuntu/dev/demo1/node_modules/webpack/lib/Compilation.js:1244:27)

Old projects created a month ago are fine. The build/generate succeed without error.

**Comment by manniL** [comment]
see https://github.com/nuxt/nuxt.js/issues/4931
