### ISSUE TITLE
Vuetify breaks fresh install 

### ISSUE THREAD

**Issue by durduliu2009** [nuxt/create-nuxt-app#219]
Hello guys,
After following this procedure from https://nuxtjs.org/guide/installation#using-nuxt-js-starter-template it seems that vuetify initialization has some problems.
Can anyone help ? 

vue --version = 3.5.5

```

 WARN  window is not defined                                                                 20:40:21

  at Object.<anonymous> (node_modules\vuetify\es5\util\helpers.js:176:5)
  at Module._compile (internal/modules/cjs/loader.js:689:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
  at Module.load (internal/modules/cjs/loader.js:599:32)
  at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
  at Module._load (internal/modules/cjs/loader.js:530:3)
  at Function._load (node_modules\vuetify-loader\lib\matcher\generator.js:8:15)
  at Module.require (internal/modules/cjs/loader.js:637:17)
  at require (internal/modules/cjs/helpers.js:22:18)
  at Object.<anonymous> (node_modules\vuetify\es5\components\VIcon\VIcon.js:29:16)
  at Module._compile (internal/modules/cjs/loader.js:689:30)
  at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
  at Module.load (internal/modules/cjs/loader.js:599:32)
  at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
  at Module._load (internal/modules/cjs/loader.js:530:3)
  at Function._load (node_modules\vuetify-loader\lib\matcher\generator.js:8:15)


 WARN  window is not defined                                                                 20:40:54

  at Module../node_modules/vuetify/lib/util/helpers.js (server.js:32749:3)
  at __webpack_require__ (server.js:27:30)
  at Module../node_modules/vuetify/lib/components/Vuetify/mixins/lang.js (server.js:26682:71)
  at __webpack_require__ (server.js:27:30)
  at Module../node_modules/vuetify/lib/components/Vuetify/index.js (server.js:26198:70)
  at __webpack_require__ (server.js:27:30)
  at Module../node_modules/vuetify/lib/index.js (server.js:28001:77)
  at __webpack_require__ (server.js:27:30)
  at Module../layouts/default.vue (server.js:2058:69)
  at __webpack_require__ (server.js:27:30)
```

Those warn messages appear when I run `yarn dev`

**Comment by durduliu2009** [comment]
Hmm it seems that vuetify fixed it in https://github.com/vuetifyjs/vuetify/issues/6952. I will come back after I will test it

**Comment by durduliu2009** [comment]
I've tested it and it is working.
