### ISSUE TITLE
Error running tests with Jest

### ISSUE THREAD

**Issue by zamakkat** [nuxt/create-nuxt-app#259]
Created a new project and selected Jest as the testing framwork. Running into an issue with it though. Node version 10.16.0, npx version 10.2.0.

Using the command "npx create-nuxt-app" and the following options:

Use a custom server framework: Express
Choose features to install:
- Progressive Web App (PWA) Support
- Linter / Formatter
- Axios

Use a custom UI framework: none
Use a custom test framework: jest
Choose rendering mode: Universal
Choose a package manager: npm

When running `npm run test` get the following error:
```
 FAIL  test/Logo.spec.js
  Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    ~/sample-project/test/Logo.spec.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { mount } from '@vue/test-utils';
                                                                                                    ^

    SyntaxError: Unexpected token {

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:471:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:513:25)

Running coverage on untested files...Failed to collect coverage from ~/sample-project/pages/index.vue
ERROR: ~/sample-project/pages/index.vue: 'import' and 'export' may only appear at the top level (28:0)

  26 | //
  27 | //
> 28 | import Logo from '~/components/Logo.vue';
     | ^
  29 | export default {
  30 |   components: {
  31 |     Logo
STACK: SyntaxError: ~/sample-project/pages/index.vue: 'import' and 'export' may only appear at the top level (28:0)

  26 | //
  27 | //
> 28 | import Logo from '~/components/Logo.vue';
     | ^
  29 | export default {
  30 |   components: {
  31 |     Logo
    at Parser.raise (~/sample-project/node_modules/@babel/parser/lib/index.js:6344:17)
    at Parser.parseStatementContent (~/sample-project/node_modules/@babel/parser/lib/index.js:9879:18)
    at Parser.parseStatement (~/sample-project/node_modules/@babel/parser/lib/index.js:9788:17)
    at Parser.parseBlockOrModuleBlockBody (~/sample-project/node_modules/@babel/parser/lib/index.js:10364:25)
    at Parser.parseBlockBody (~/sample-project/node_modules/@babel/parser/lib/index.js:10351:10)
    at Parser.parseBlock (~/sample-project/node_modules/@babel/parser/lib/index.js:10335:10)
    at Parser.parseFunctionBody (~/sample-project/node_modules/@babel/parser/lib/index.js:9408:24)
    at Parser.parseFunctionBodyAndFinish (~/sample-project/node_modules/@babel/parser/lib/index.js:9378:10)
    at withTopicForbiddingContext (~/sample-project/node_modules/@babel/parser/lib/index.js:10498:12)
    at Parser.withTopicForbiddingContext (~/sample-project/node_modules/@babel/parser/lib/index.js:9683:14)
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|
Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.231s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sample-project@1.0.0 test: `jest`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sample-project@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by zamakkat** [comment]
Hmm strange seems to work after I restarted my machine. Will close then.
