### ISSUE TITLE
[error] choose UI Framework 'framevuerk' Failed to compile errors

### ISSUE THREAD

**Issue by takehiro-takahashi** [nuxt/create-nuxt-app#302]
choose
```
? Choose the package manager Yarn
? Choose UI framework Framevuerk
? Choose custom server framework Fastify
? Choose Nuxt.js modules (Press <space> to select, <a> to toggle all, <i> to invert selection)
? Choose linting tools ESLint
? Choose test framework Jest
? Choose rendering mode Universal (SSR)
```

error
```
(node:25230) UnhandledPromiseRejectionWarning: Error: Could not compile template projects/node_modules/@nuxt/vue-app/template/App.js: Cannot resolve "framevuerk/dist/framevuerk-nuxt.min.css" from "projects/framevuerk/dist/framevuerk-nuxt.min.css"
    at projects/node_modules/@nuxt/builder/dist/builder.js:5945:17
    at async Promise.all (index 0)
    at async Builder.compileTemplates (projects/node_modules/@nuxt/builder/dist/builder.js:5924:5)
    at async Builder.generateRoutesAndFiles (projects/node_modules/@nuxt/builder/dist/builder.js:5658:5)
    at async Builder.build (projects/node_modules/@nuxt/builder/dist/builder.js:5575:5)
    at async start (projectsserver/index.js:22:5)
(node:25230) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:25230) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by clarkdo** [comment]
@nainemom I corrected the css name (maybe should be changed in framevuerk-builder side), but it still has some errors, could you have a look ?

Error in `framevuerk-builder`:

```sh
$ framevuerk-builder -c ./framevuerk-config.js
 ERROR  Failed to compile with 64 errors                                                    09:28:50

These relative modules were not found:

* ./fvContent.vue?vue&type=style&index=0&lang=scss& in ./node_modules/framevuerk/src/components/fvCo
ntent.vue
* ./fvFooter.vue?vue&type=style&index=0&lang=scss& in ./node_modules/framevuerk/src/components/fvFooter.vue
```

In nuxt dev, this error only happens in `framevuerk` template:

```sh
 ERROR  Failed to compile with 1 errors                                   friendly-errors 09:25:05

This relative module was not found:                                       friendly-errors 09:25:05
                                                                          friendly-errors 09:25:05
* ./components/nuxt-error.vue in ./.nuxt/index.js 
```

**Comment by nainemom** [comment]
I realized that Ali doesn't respect `npm-shrinkwrap.json` file that I used in `framevuerk-builder` package. I'm working on it inside [this](https://github.com/framevuerk/framevuerk-builder) repo and also let you know when it's finished.

**Comment by nainemom** [comment]
@clarkdo It's fixed now. I changed the installation steps of `framevuerk-builder` (manually install dependencies in `postinstall` script) and published a new patch version of that on the npm registry. So now it's fixed and should work via both `npm` and `yarn` without any changes in this repo.

**Comment by clarkdo** [comment]
@nainemom Great work,thank you so much !
@takehiro-takahashi Could you try again?

**Comment by takehiro-takahashi** [comment]
@clarkdo 
Thank you so much !
It worked without problems!

@nainemom 
Thank you so much !
You responded quickly and I was saved a lot!
