### ISSUE TITLE
为什么window安装nuxt.js 报错呢？

### ISSUE THREAD

**Issue by 17838963114wu** [nuxt/create-nuxt-app#341]
Error: EPERM: operation not permitted, mkdir 'C:\Users\MIDAI'
TypeError: Cannot read property 'get' of undefined
    at errorMessage (D:\node\node_modules\npm\lib\utils\error-message.js:38:39)
    at errorHandler (D:\node\node_modules\npm\lib\utils\error-handler.js:201:13)
    at D:\node\node_modules\npm\bin\npm-cli.js:78:20
    at cb (D:\node\node_modules\npm\lib\npm.js:225:22)
    at D:\node\node_modules\npm\lib\npm.js:263:24
    at D:\node\node_modules\npm\lib\config\core.js:83:7
    at Array.forEach (<anonymous>)
    at D:\node\node_modules\npm\lib\config\core.js:82:13
    at f (D:\node\node_modules\npm\node_modules\once\once.js:25:25)
    at afterExtras (D:\node\node_modules\npm\lib\config\core.js:173:20)
D:\node\node_modules\npm\lib\utils\error-handler.js:97
  var doExit = npm.config.loaded ? npm.config.get('_exit') : true
                          ^

TypeError: Cannot read property 'loaded' of undefined
    at exit (D:\node\node_modules\npm\lib\utils\error-handler.js:97:27)
    at process.errorHandler (D:\node\node_modules\npm\lib\utils\error-handler.js:216:3)
    at process.emit (events.js:209:13)
    at process._fatalException (internal/process/execution.js:150:25)
Install for [ 'create-nuxt-app@latest' ] failed with code 7

**Comment by clarkdo** [comment]
可以提供一下具体重现问题的步骤么？
