### ISSUE TITLE
TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by NavaneethVijay** [nuxt/create-nuxt-app#351]
I'm facing the following error while fresh installation of nuxt project, initially i was getting the same issue #349 after following up the comments I have a new issue while creating the nuxt app. [Windows]

`npx create-nuxt-app@2.10.1 admin`

```
Error: EEXIST: file already exists, mkdir 'C:\Users\Navaneeth'
TypeError: Cannot read property 'get' of undefined
    at errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205:18)
    at C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js:78:20
    at cb (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:228:22)
    at C:\Program Files\nodejs\node_modules\npm\lib\npm.js:266:24
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:83:7
    at Array.forEach (<anonymous>)
    at C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:82:13
    at f (C:\Program Files\nodejs\node_modules\npm\node_modules\once\once.js:25:25)
    at afterExtras (C:\Program Files\nodejs\node_modules\npm\lib\config\core.js:173:20)
    at C:\Program Files\nodejs\node_modules\npm\node_modules\mkdirp\index.js:47:53
C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205
  if (npm.config.get('json')) {
                 ^

TypeError: Cannot read property 'get' of undefined
    at process.errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205:18)
    at process.emit (events.js:182:13)
    at process._fatalException (internal/bootstrap/node.js:628:27)
Install for create-nuxt-app@2.10.0 failed with code 7
```
Node version: v11.1.0
npm version: 6.4.1

**Comment by padri-zan** [comment]
please read this
[Click this link to redirect to stackoverflow](https://stackoverflow.com/questions/42678759/npm-error-on-every-command-eexist-file-already-exists-mkdir-c-users-user-ap)

**Comment by aldarund** [comment]
try 2,11,1 ( e.g. latest one )

**Comment by aldarund** [comment]
It seems to be resolved, closing. In case its still issue please open a new
