### ISSUE TITLE
Getting error on create-next-app

### ISSUE THREAD

**Issue by mozaman** [nuxt/create-nuxt-app#377]
Cant seem to install on Mac OS Catalina. Any help appreciated.

Getting the below:

`npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! fibers@4.0.2 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the fibers@4.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/M/.npm/_logs/2019-11-18T18_26_05_124Z-debug.log

> fibers@4.0.2 install /Users/X/Desktop/Projects/X/node_modules/fibers
> node build.js || nodejs build.js

/Users/X/.npm/_npx/5465/lib/node_modules/create-nuxt-app/node_modules/sao/lib/installPackages.js:108
        throw new SAOError(`Failed to install ${packageName} in ${cwd}`)
        ^

Error: Failed to install packages in /Users/X/Desktop/Projects/X
    at ChildProcess.ps.on.code (/Users/X/.npm/_npx/5465/lib/node_modules/create-nuxt-app/node_modules/sao/lib/installPackages.js:108:15)
    at ChildProcess.emit (events.js:197:13)
    at maybeClose (internal/child_process.js:984:16)
    at Socket.stream.socket.on (internal/child_process.js:401:11)
    at Socket.emit (events.js:197:13)
    at Pipe._handle.close (net.js:611:12)
Mac:Projects M$ 
`

**Comment by mozaman** [comment]
Solved by updating node to latest version

> Cant seem to install on Mac OS Catalina. Any help appreciated.
> 
> Getting the below:
> 
> `npm ERR! file sh npm ERR! code ELIFECYCLE npm ERR! errno ENOENT npm ERR! syscall spawn npm ERR! fibers@4.0.2 install: `node build.js || nodejs build.js`
> npm ERR! spawn ENOENT
> npm ERR!
> npm ERR! Failed at the fibers@4.0.2 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional log
> ging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR! /Users/M/.npm/_logs/2019-11-18T18_26_05_124Z-debug.log
> 
> > fibers@4.0.2 install /Users/X/Desktop/Projects/X/node_modules/fibers
> > node build.js || nodejs build.js
> 
> /Users/X/.npm/_npx/5465/lib/node_modules/create-nuxt-app/node_modules/sao/lib/installPackages.js:108
> throw new SAOError(`Failed to install ${packageName} in ${cwd}`)
> ^
> 
> Error: Failed to install packages in /Users/X/Desktop/Projects/X
> at ChildProcess.ps.on.code (/Users/X/.npm/_npx/5465/lib/node_modules/create-nuxt-app/node_modules/sao/lib/installPackages.js:108:15)
> at ChildProcess.emit (events.js:197:13)
> at maybeClose (internal/child_process.js:984:16)
> at Socket.stream.socket.on (internal/child_process.js:401:11)
> at Socket.emit (events.js:197:13)
> at Pipe._handle.close (net.js:611:12)
> Mac:Projects M$
> `
