### ISSUE TITLE
Newly generated nuxt app fails with core-js and fibers errors

### ISSUE THREAD

**Issue by JairBear** [nuxt/create-nuxt-app#422]
ubuntu 18.04

making a nuxt app has never been a problem before, suddenly im getting core-js and fibers errors.

myself@myself:~/Documents$ nodejs -v
v13.7.0
myself@myself:~/Documents$ npm -v
6.13.6
myself@myself:~/Documents$ npx -v
6.13.6
myself@myself:~/Documents$ npx create-nuxt-app test-app

create-nuxt-app v2.12.0
✨  Generating Nuxt.js project in test-app
? Project name test-app
? Project description My tiptop Nuxt.js project
? Author name Myself
? Choose the package manager Npm
? Choose UI framework Vuetify.js
? Choose custom server framework Express
? Choose Nuxt.js modules Axios
? Choose linting tools (Press <space> to select, <a> to toggle all, <i> to inver
t selection)
? Choose test framework None
? Choose rendering mode Single Page App
? Choose development tools (Press <space> to select, <a> to toggle all, <i> to i
nvert selection)
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not r
ecommended for usage due to the number of issues. Please, upgrade your dependenc
ies to the actual version of core-js@3.
make ✖ ERR  Missing Makefile / Bakefile 
make ℹ info Run "make init" to generate a Makefile.
Build succeeded but target not found
make ✖ ERR  Missing Makefile / Bakefile 
make ℹ info Run "make init" to generate a Makefile.
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not r
ecommended for usage due to the number of issues. Please, upgrade your dependenc
ies to the actual version of core-js@3.
make ✖ ERR  Missing Makefile / Bakefile 
make ℹ info Run "make init" to generate a Makefile.
Build succeeded but target not found
make ✖ ERR  Missing Makefile / Bakefile 
make ℹ info Run "make init" to generate a Makefile.
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not r
ecommended for usage due to the number of issues. Please, upgrade your dependenc
ies to the actual version of core-js@3.
make ✖ ERR  Missing Makefile / Bakefile 
make ℹ info Run "make init" to generate a Makefile.
Build succeeded but target not found
make ✖ ERR  Missing Makefile / Bakefile 
make ℹ info Run "make init" to generate a Makefile.
Build succeeded but target not found
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/wa
tchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"
})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/no
demon/node_modules/fsevents):
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not r
ecommended for usage due to the number of issues. Please, upgrade your dependenc
ies to the actual version of core-js@3.
make ✖ ERR  Missing Makefile / Bakefile 
make ℹ info Run "make init" to generate a Makefile.
Build succeeded but target not found
make ✖ ERR  Missing Makefile / Bakefile 
make ℹ info Run "make init" to generate a Makefile.
Build succeeded but target not found
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/wa
tchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"
})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/no
demon/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not r
ecommended for usage due to the number of issues. Please, upgrade your dependenc
ies to the actual version of core-js@3.
make ✖ ERR  Missing Makefile / Bakefile 
make ℹ info Run "make init" to generate a Makefile.
Build succeeded but target not found
make ✖ ERR  Missing Makefile / Bakefile 
make ℹ info Run "make init" to generate a Makefile.
Build succeeded but target not found
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/wa
tchpack/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"
})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/no
demon/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"
})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fse
vents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"}
)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fibers@4.0.2 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fibers@4.0.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/myself/.npm/_logs/2020-02-04T06_36_26_385Z-debug.log

> fibers@4.0.2 install /home/myself/Documents/test-app/node_modules/fibers
> node build.js || nodejs build.js

ddddddddd/home/myself/.npm/_npx/10232/lib/node_modules/create-nuxt-app/node_modules/sao/lib/installPackages.js:108
        throw new SAOError(`Failed to install ${packageName} in ${cwd}`)
        ^

SAOError: Failed to install packages in /home/myself/Documents/test-app
    at ChildProcess.<anonymous> (/home/myself/.npm/_npx/10232/lib/node_modules/create-nuxt-app/node_modules/sao/lib/installPackages.js:108:15)
    at ChildProcess.emit (events.js:321:20)
    at maybeClose (internal/child_process.js:1026:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5) {
  __sao: true
}
myself@myself:~/Documents$

**Comment by JairBear** [comment]
Closing issue as it is already opened here: https://github.com/nuxt/create-nuxt-app/issues/184
