### ISSUE TITLE
When creating a project, selecting Vuetify results in an error.

### ISSUE THREAD

**Issue by EunChan0817** [nuxt/create-nuxt-app#447]
SAOError: Failed to install packages in ....

...

.config/yarn/global/node_modules/sao/lib/installPackages.js:108:15)
    at ChildProcess.emit (events.js:321:20)
    at maybeClose (internal/child_process.js:1026:16)
    at Socket.<anonymous> (internal/child_process.js:441:11)
    at Socket.emit (events.js:321:20)
    at Pipe.<anonymous> (net.js:668:12) {
  __sao: true
}

**Comment by clarkdo** [comment]
Duplicate of https://github.com/nuxt/create-nuxt-app/issues/441
