### ISSUE TITLE
SAOError: Failed to install packages

### ISSUE THREAD

**Issue by Anas-Alwindawee** [nuxt/create-nuxt-app#494]
Hi 

I'm getting below error when creating new nuxt app, I tried to clear the npm cache and installed essential build packages but with no chance,

WSL Ubuntu 20.04 LTS, node v12.16.2, npm v6.14.4, below was my choices and the errors I get,

anas@DESKTOP-VENR4M1:~$ npx create-nuxt-app test-nuxt

create-nuxt-app v2.15.0
✨ Generating Nuxt.js project in test-nuxt
? Project name test-nuxt
? Project description My posh Nuxt.js project
? Author name Anas
? Choose programming language JavaScript
? Choose the package manager Npm
? Choose UI framework Vuetify.js
? Choose custom server framework None (Recommended)
? Choose Nuxt.js modules (Press to select, to toggle all, to invert selection)
? Choose linting tools ESLint, Prettier
? Choose test framework None
? Choose rendering mode Single Page App
? Choose development tools jsconfig.json (Recommended for VS Code)
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm ERR! Unexpected end of JSON input while parsing near '...jdBkOYpTVM3Y085qWei\n'

npm ERR! A complete log of this run can be found in:
npm ERR! /home/anas/.npm/_logs/2020-04-24T11_38_37_366Z-debug.log

/home/anas/.npm/_npx/4182/lib/node_modules/create-nuxt-app/node_modules/sao/lib/installPackages.js:108
throw new SAOError(Failed to install ${packageName} in ${cwd})
^

SAOError: Failed to install packages in /home/anas/test-nuxt
at ChildProcess. (/home/anas/.npm/_npx/4182/lib/node_modules/create-nuxt-app/node_modules/sao/lib/installPackages.js:108:15)
at ChildProcess.emit (events.js:310:20)
at maybeClose (internal/child_process.js:1021:16)
at Socket. (internal/child_process.js:443:11)
at Socket.emit (events.js:310:20)
at Pipe. (net.js:672:12) {

__sao: true
}

The complete run log.
[2020-04-24T11_38_37_366Z-debug.log.txt](https://github.com/nuxt/create-nuxt-app/files/4528627/2020-04-24T11_38_37_366Z-debug.log.txt)

**Comment by kkukelka** [comment]
I ran into difficulties while creating a nuxt-app via npx create-nuxt-app today as well. (Mac OSX 10.14.6, Node v13.9.0)
```
Trace: Error: No valid exports main found for 'Trace: Error: No valid exports main found for '/Users/kilian/.npm/_npx/6379/lib/node_modules/create-nuxt-app/node_modules/is-promise'
    at resolveExportsTarget (internal/modules/cjs/loader.js:632:9)
    at applyExports (internal/modules/cjs/loader.js:500:14)
    at resolveExports (internal/modules/cjs/loader.js:549:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:664:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:967:27)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/kilian/.npm/_npx/6379/lib/node_modules/create-nuxt-app/node_modules/run-async/index.js:3:17)
    at Module._compile (internal/modules/cjs/loader.js:1151:30) {
  code: 'MODULE_NOT_FOUND'
}
```
Not sure if related to the problem stated above, since error gets thrown before I even reach the options dialogue.

**Comment by myokoym** [comment]
Hi, I ran into the same error (SAOError), but it worked by run `npm install` manually.

```
% npx create-nuxt-app my-project
...
SAOError: Failed to install packages in ...
...
% cd my-project
% npm install
...
% npm run dev
```

**Comment by Anas-Alwindawee** [comment]
Hi,

I tried the suggested steps however its did not fix the issue, and tried many other things like clear the cache of npm manually with no chance, then I decide to move to cloud development environment where all my problems solved.

BR

**Comment by Ebi-web** [comment]
> Hi, I ran into the same error (SAOError), but it worked by run `npm install` manually.
> 
> ```
> % npx create-nuxt-app my-project
> ...
> SAOError: Failed to install packages in ...
> ...
> % cd my-project
> % npm install
> ...
> % npm run dev
> ```

Executing `yarn install` instead of `npm install` worked!
