### ISSUE TITLE
Problem with yarn dev command

### ISSUE THREAD

**Issue by K0G4M1** [nuxt/create-nuxt-app#593]
yarn dev
yarn run v1.21.1
$ nuxt
i Parsed 1 files in 0,0 seconds                                                                 @nuxt/content 12:54:57

   ╭───────────────────────────────────────╮
   │                                                                                                 │
   │   Nuxt.js @ v2.14.3                                                                   │ 
   │                                                                                                 │
   │   ▸ Environment: development                                                 │
   │   ▸ Rendering:   server-side                                                      │
   │   ▸ Target:      server                                                                 │
   │                                                                                                 │
   │   Listening: http://localhost:3000/                                             │
   │                                                                                                 │
   ╰───────────────────────────────────────╯

i Preparing project for development                                                                           12:55:00
i Initial build may take a while                                                                              12:55:00

 WARN  Components directory not found: ~/components/global                                                    12:55:00

√ Builder initialized                                                                                         12:55:00
√ Nuxt files generated                                                                                        12:55:00

 ERROR  Plugin not found: F:\[__PROJECTS__]\web\Nuxt.js\netlify-cms\.nuxt\components\plugin.js                12:55:00

  at node_modules\@nuxt\builder\dist\builder.js:6075:15
  at async Promise.all (index 0)
  at async Builder.build (node_modules\@nuxt\builder\dist\builder.js:5640:5)
  at async Object._buildDev (node_modules\@nuxt\cli\dist\cli-dev.js:106:5)
  at async Object.startDev (node_modules\@nuxt\cli\dist\cli-dev.js:64:7)
  at async Object.run (node_modules\@nuxt\cli\dist\cli-dev.js:51:5)
  at async NuxtCommand.run (node_modules\@nuxt\cli\dist\cli-index.js:2810:7)

thanks in advance for the help

**Comment by K0G4M1** [comment]
I use this config when create the project

Language: Javascript
Package manager: Yarn
UI framework: Vuetify.js
Modules: [ Axios, Content, PWA ]
Linting: ESLint
Testing: None
Rendering mode: Universal
Target: Server

**Comment by nelsonlarocca** [comment]
I just moved one folder to Nuxt components and got the same warning !

**Comment by manuel-gutierrez** [comment]
I'm having the same problem. Any one have a guess on this?

**Comment by debs-obrien** [comment]
Its just a warning to tell you that there is no global folder inside components. This is only needed if you want to add components inside your markdown without having to write any import statements. So it should be more a friendly tip than a warning in my opinion. We could also add it to create nuxt-app with a readMe inside explaining what it does 🧐

**Comment by manuel-gutierrez** [comment]
Hi @debs-obrien ! Thanks for taking the time to reply. "We could also add it to create nuxt-app with a readMe inside explaining what it does" Good call! as fo newbies as my self will save us time. :)

**Comment by sctnightcore** [comment]
any news ? how to fix it ?

**Comment by mahesh2237** [comment]
I am stuck on this from last two days can't found any solution

**Comment by mahesh2237** [comment]
But that issue only come when auto import component by using components: true in nuxt.config.js. If components:false set than working fine

**Comment by ICTLAYER** [comment]
╭───────────────────────────────────────╮
   │                                       │
   │   Nuxt @ v2.15.8                      │
   │                                       │
   │   ▸ Environment: development          │
   │   ▸ Rendering:   server-side          │
   │   ▸ Target:      static               │
   │                                       │
   │   Listening: http://localhost:3000/   │
   │                                       │
   ╰───────────────────────────────────────╯

i Preparing project for development                                                                                                                                                           20:47:42
i Initial build may take a while                                                                                                                                                              20:47:42  
i Discovered Components: .nuxt/components/readme.md                                                                                                                                           20:47:42
√ Builder initialized                                                                                                                                                                         20:47:42  
√ Nuxt files generated                                                                                                                                                                        20:47:42

 ERROR  Plugin not found: C:\Users\akaas\Documents\GitHub\pachmisheli\.nuxt\components\plugin.js                                                                                              20:47:42  

  at node_modules\@nuxt\builder\dist\builder.js:740:15
  at async Promise.all (index 0)
  at async Builder.build (node_modules\@nuxt\builder\dist\builder.js:324:5)
  at async Object._buildDev (node_modules\@nuxt\cli\dist\cli-dev.js:107:5)
  at async Object.startDev (node_modules\@nuxt\cli\dist\cli-dev.js:65:7)
  at async Object.run (node_modules\@nuxt\cli\dist\cli-dev.js:52:5)
  at async NuxtCommand.run (node_modules\@nuxt\cli\dist\cli-index.js:413:7)
  ===========================================================
  same problem !!!!!!!!!!!!!!!!!!!!

**Comment by ICTLAYER** [comment]
> ERROR Plugin not found:

**Comment by mahesh2237** [comment]
I watch too many video and read many articles but problems continues come, for now i set components:false in nuxt.config.js and it's run. it's not a proper solution but for now I doing other basic staff 
![image](https://user-images.githubusercontent.com/14051908/168430846-0508494e-6b53-47d7-b785-5d52c8c0ca11.png)

**Comment by ElyFura** [comment]
`npm i --save glob@7.2.0` fixed it for me

Disabling the components just lead to another errors

**Comment by MarienMupenda** [comment]
This problem seems to appear only on windows.

**Comment by MarienMupenda** [comment]
After trying the @ElyFura's tip i had to run the below command to get rid of all the errors
`export NODE_OPTIONS=--openssl-legacy-provider`

**Comment by mahesh2237** [comment]
I tried in ubuntu after run export NODE_OPTIONS=--openssl-legacy-provider, it's working fine

**Comment by mahesh2237** [comment]
but on windows no solutions work

**Comment by MarienMupenda** [comment]
I my case the problem, was the node version i was using on my Windows 11.
I was using 17.x, I switched to 16 and the problem was gone.
You will find in the documentation [nuxtjs.org](https://nuxtjs.org/docs/get-started/installation) that the LTS is the version to use.

**Comment by mahesh2237** [comment]
@MarienMupenda thanks bro, finally fixed. same issue

after switch latest stable version of node js which is 16.5 and latest nuxtjs verison which is currently 2.15.8, my issue is finally fixed.

So that's the issue because of nuxtjs and nodjs lts verison mismatch. Really Thanks

**Comment by MarienMupenda** [comment]
You're welcome @mahesh2237, happy coding!
