### ISSUE TITLE
Can't create a new application with npm, npx, yarn

### ISSUE THREAD

**Issue by HuseyinKaplay** [nuxt/create-nuxt-app#600]
Hi everyone, I installed **create-nuxt-app** as global
`npm install -g create-nuxt-app`

And when try to create a new application
`create-nuxt-app first-application`

Get this error:

```
internal/modules/cjs/loader.js:628
  throw e;
  ^

Error: No valid exports main found for '/usr/local/lib/node_modules/create-nuxt-app/node_modules/cac'
    at resolveExportsTarget (internal/modules/cjs/loader.js:625:9)
    at applyExports (internal/modules/cjs/loader.js:502:14)
    at resolveExports (internal/modules/cjs/loader.js:551:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:657:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:960:27)
    at Function.Module._load (internal/modules/cjs/loader.js:855:27)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/create-nuxt-app/lib/cli.js:5:13)
    at Module._compile (internal/modules/cjs/loader.js:1144:30) {
  code: 'MODULE_NOT_FOUND'
}
```

**Comment by jflores1** [comment]
@HuseyinKaplay I was having the same problem. I updated node from v13.x to v14.2 and it worked.

**Comment by HuseyinKaplay** [comment]
@jflores1 yes, it solve.
