### ISSUE TITLE
error creating new project - error fibers

### ISSUE THREAD

**Issue by solitarymx** [nuxt/create-nuxt-app#659]
I'm try npx-yarn-npm and npm init nuxt-app, dont work! Still fibers error.

Windows 10 x64
node 14.15.0 LTS
npm 6.14.8
python 2.7
yarn 2.3.3

...
39411 silly saveTree `-- prettier@2.1.2
39412 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\chokidar\node_modules\fsevents):
39413 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
39414 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
39414 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
39414 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
39414 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
39415 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\watchpack-chokidar2\node_modules\chokidar\node_modules\fsevents):
39416 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
39417 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
39417 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
39417 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
39417 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
39418 warn eslint-plugin-vue@6.2.2 requires a peer of eslint@^5.0.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
39419 verbose stack Error: fibers@4.0.3 install: `node build.js || nodejs build.js`
39419 verbose stack Exit status 1
39419 verbose stack     at EventEmitter.<anonymous> (C:\Users\mhy\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
39419 verbose stack     at EventEmitter.emit (events.js:315:20)
39419 verbose stack     at ChildProcess.<anonymous> (C:\Users\mhy\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
39419 verbose stack     at ChildProcess.emit (events.js:315:20)
39419 verbose stack     at maybeClose (internal/child_process.js:1048:16)
39419 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
39420 verbose pkgid fibers@4.0.3
39421 verbose cwd C:\Users\mhy\projects\nuxt-projects\testapp
39422 verbose Windows_NT 10.0.19042
39423 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mhy\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install"
39424 verbose node v14.15.0
39425 verbose npm  v6.14.8
39426 error code ELIFECYCLE
39427 error errno 1
39428 error fibers@4.0.3 install: `node build.js || nodejs build.js`
39428 error Exit status 1
39429 error Failed at the fibers@4.0.3 install script.
39429 error This is probably not a problem with npm. There is likely additional logging output above.
39430 verbose exit [ 1, true ]

**Comment by solitarymx** [comment]
Now try again and change vuetify to bulma and iView created successfully, used npx
I guess only vuetify error.

**Comment by solitarymx** [comment]
Try again and not select framework, using yarn but not this time eslint error.

...
Oops! Something went wrong! :(
ESLint: 7.13.0
ESLint couldn't find the plugin "eslint-plugin-import".
(The package "eslint-plugin-import" was not found when loaded as a Node module from the directory "C:\Users\mhy\projects\nuxt-projects\nuxttest3".)
It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:
    npm install eslint-plugin-import@latest --save-dev
The plugin "eslint-plugin-import" was referenced from the config file in ".eslintrc.js » @nuxtjs/eslint-config-typescript » @nuxtjs/eslint-config".
...

**Comment by frm-adiputra** [comment]
No errors when using node v12.20.0
