### ISSUE TITLE
Create nuxt app failed.

### ISSUE THREAD

**Issue by twn39** [nuxt/create-nuxt-app#683]
It's run failed when I create a blank project use create-nuxt-app, the command line options:

```
➤ npx create-nuxt-app forumweb                                                                                                 (base) 

create-nuxt-app v3.4.0
✨  Generating Nuxt.js project in forumweb
? Project name: forumweb
? Programming language: TypeScript
? Package manager: Npm
? UI framework: Chakra UI
? Nuxt.js modules: Progressive Web App (PWA)
? Linting tools: Prettier
? Testing framework: None
? Rendering mode: Universal (SSR / SSG)
? Deployment target: Server (Node.js hosting)
? Development tools: jsconfig.json (Recommended for VS Code if you're not using typescript)
? Continuous integration: None
? Version control system: Git
```

and the errors:

```
➤ npm run dev                                                                                                                  (base) 

> forumweb@1.0.0 dev /Users/xxxxx/apps/myapps/forumweb
> nuxt-ts


 FATAL  Must use import to load ES Module: /Users/xxxxx/apps/myapps/forumweb/node_modules/lodash-es/merge.js             14:13:37
require() of ES modules is not supported.
require() of /Users/xxxxx/apps/myapps/forumweb/node_modules/lodash-es/merge.js from /Users/xxxxx/apps/myapps/forumweb/node_modul
es/@chakra-ui/vue/src/utils/icons.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "modu
le" which defines all .js files in that package scope as ES modules.
Instead rename merge.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/xxxxx/app
s/myapps/forumweb/node_modules/lodash-es/package.json.


  Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: node_modules/lodash-es/merge.js
  require() of ES modules is not supported.
  require() of node_modules/lodash-es/merge.js from /Users/xxxxx/apps/myapps/forumweb/node_modules/@chakra-ui/vue/src/utils/icons.j
s is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in 
that package scope as ES modules.
  Instead rename merge.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from node_modules/loda
sh-es/package.json.
  
  at Module._extensions..js (internal/modules/cjs/loader.js:1031:13)
  at Object.require.extensions.<computed> (node_modules/ts-node/src/index.ts:1045:43)


   ╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                                                 │
   │   ✖ Nuxt Fatal Error                                                                                            │
   │                                                                                                                 │
   │   Error [ERR_REQUIRE_ESM]: Must use import to load ES Module:                                                   │
   │   /Users/xxxxx/apps/myapps/forumweb/node_modules/lodash-es/merge.js                                          │
   │   require() of ES modules is not supported.                                                                     │
   │   require() of /Users/xxxx/apps/myapps/forumweb/node_modules/lodash-es/merge.js from                        │
   │   /Users/xxxxx/apps/myapps/forumweb/node_modules/@chakra-ui/vue/src/utils/icons.js is an ES module file as   │
   │   it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in   │
   │   that package scope as ES modules.                                                                             │
   │   Instead rename merge.js to end in .cjs, change the requiring code to use import(), or remove "type":          │
   │   "module" from /Users/xxxxx/apps/myapps/forumweb/node_modules/lodash-es/package.json.                       │
   │                                                                                                                 │
   │                                                                                                                 │
   ╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! forumweb@1.0.0 dev: `nuxt-ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the forumweb@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxxx/.npm/_logs/2021-01-04T06_13_37_323Z-debug.log
```

**Comment by clarkdo** [comment]
Fixed in v3.5.0
