### ISSUE TITLE
Can't create a fresh Nuxt project

### ISSUE THREAD

**Issue by begueradj** [nuxt/create-nuxt-app#844]
What I did, the process and the output are all below:

```

begueradj@FA512:~/Development/Nuxt$ yarn create nuxt-app nv2
yarn create v1.22.5
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...

success Installed "create-nuxt-app@3.7.1" with binaries:
      - create-nuxt-app

create-nuxt-app v3.7.1
✨  Generating Nuxt.js project in nv2
? Project name: nv2
? Programming language: JavaScript
? Package manager: Yarn
? UI framework: Vuetify.js
? Nuxt.js modules: Axios - Promise based HTTP client
? Linting tools: ESLint
? Testing framework: Jest
? Rendering mode: Universal (SSR / SSG)
? Deployment target: Server (Node.js hosting)
? Development tools: jsconfig.json (Recommended for VS Code if you're not using 
typescript)
? Continuous integration: None
? Version control system: Git
warning nuxt > @nuxt/babel-preset-app > core-js@2.6.12: core-js@<3.3 is no longe
warning nuxt > @nuxt/babel-preset-app > core-js@2.6.12: core-js@<3.3 is no longe
r maintained and not recommended for usage due to the number of issues. Because 
of the V8 engine whims, feature detection in old core-js versions could cause a 
warning nuxt > @nuxt/babel-preset-app > core-js@2.6.12: core-js@<3.3 is no longe
r maintained and not recommended for usage due to the number of issues. Because 
of the V8 engine whims, feature detection in old core-js versions could cause a 
warning nuxt > @nuxt/babel-preset-app > core-js@2.6.12: core-js@<3.3 is no longe
r maintained and not recommended for usage due to the number of issues. Because 
of the V8 engine whims, feature detection in old core-js versions could cause a 
slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependen
cies to the actual version of core-js.
warning nuxt > @nuxt/babel-preset-app > core-js@2.6.12: core-js@<3.3 is no longe
r maintained and not recommended for usage due to the number of issues. Because 
of the V8 engine whims, feature detection in old core-js versions could cause a 
slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependen
cies to the actual version of core-js.
warning nuxt > @nuxt/webpack > webpack-hot-middleware > querystring@0.2.1: The q
uerystring API is considered Legacy. new code should use the URLSearchParams API
 instead.
warning nuxt > @nuxt/webpack > webpack > node-libs-browser > url > querystring@0
.2.0: The querystring API is considered Legacy. new code should use the URLSearc
hParams API instead.
warning nuxt > @nuxt/webpack > webpack > watchpack > watchpack-chokidar2 > choki
dar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x le
ss dependencies.
warning nuxt > @nuxt/webpack > webpack > watchpack > watchpack-chokidar2 > choki
dar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using ins
ecure binaries. Upgrade to fsevents 2.
warning nuxt > @nuxt/webpack > webpack > micromatch > snapdragon > source-map-re
warning nuxt > @nuxt/babel-preset-app > core-js@2.6.12: core-js@<3.3 is no longe
r maintained and not recommended for usage due to the number of issues. Because 
of the V8 engine whims, feature detection in old core-js versions could cause a 
slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependen
cies to the actual version of core-js.
warning nuxt > @nuxt/webpack > webpack-hot-middleware > querystring@0.2.1: The q
uerystring API is considered Legacy. new code should use the URLSearchParams API
 instead.
warning nuxt > @nuxt/webpack > webpack > node-libs-browser > url > querystring@0
.2.0: The querystring API is considered Legacy. new code should use the URLSearc
hParams API instead.
warning nuxt > @nuxt/webpack > webpack > watchpack > watchpack-chokidar2 > choki
dar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x le
ss dependencies.
warning nuxt > @nuxt/webpack > webpack > watchpack > watchpack-chokidar2 > choki
dar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using ins
ecure binaries. Upgrade to fsevents 2.
warning nuxt > @nuxt/webpack > webpack > micromatch > snapdragon > source-map-re
warning nuxt > @nuxt/babel-preset-app > core-js@2.6.12: core-js@<3.3 is no longe
r maintained and not recommended for usage due to the number of issues. Because 
of the V8 engine whims, feature detection in old core-js versions could cause a 
slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependen
cies to the actual version of core-js.
warning nuxt > @nuxt/webpack > webpack-hot-middleware > querystring@0.2.1: The q
uerystring API is considered Legacy. new code should use the URLSearchParams API
 instead.
warning nuxt > @nuxt/webpack > webpack > node-libs-browser > url > querystring@0
.2.0: The querystring API is considered Legacy. new code should use the URLSearc
hParams API instead.
warning nuxt > @nuxt/webpack > webpack > watchpack > watchpack-chokidar2 > choki
dar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x le
ss dependencies.
warning nuxt > @nuxt/webpack > webpack > watchpack > watchpack-chokidar2 > choki
dar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using ins
ecure binaries. Upgrade to fsevents 2.
warning nuxt > @nuxt/webpack > webpack > micromatch > snapdragon > source-map-re
solve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning nuxt > @nuxt/webpack > webpack > micromatch > snapdragon > source-map-re
warning nuxt > @nuxt/babel-preset-app > core-js@2.6.12: core-js@<3.3 is no longe
r maintained and not recommended for usage due to the number of issues. Because 
of the V8 engine whims, feature detection in old core-js versions could cause a 
slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependen
cies to the actual version of core-js.
warning nuxt > @nuxt/webpack > webpack-hot-middleware > querystring@0.2.1: The q
uerystring API is considered Legacy. new code should use the URLSearchParams API
 instead.
warning nuxt > @nuxt/webpack > webpack > node-libs-browser > url > querystring@0
.2.0: The querystring API is considered Legacy. new code should use the URLSearc
hParams API instead.
warning nuxt > @nuxt/webpack > webpack > watchpack > watchpack-chokidar2 > choki
dar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x le
ss dependencies.
warning nuxt > @nuxt/webpack > webpack > watchpack > watchpack-chokidar2 > choki
dar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using ins
ecure binaries. Upgrade to fsevents 2.
warning nuxt > @nuxt/webpack > webpack > micromatch > snapdragon > source-map-re
solve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning nuxt > @nuxt/webpack > webpack > micromatch > snapdragon > source-map-re
warning nuxt > @nuxt/babel-preset-app > core-js@2.6.12: core-js@<3.3 is no longe
r maintained and not recommended for usage due to the number of issues. Because 
of the V8 engine whims, feature detection in old core-js versions could cause a 
slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependen
cies to the actual version of core-js.
warning nuxt > @nuxt/webpack > webpack-hot-middleware > querystring@0.2.1: The q
uerystring API is considered Legacy. new code should use the URLSearchParams API
 instead.
warning nuxt > @nuxt/webpack > webpack > node-libs-browser > url > querystring@0
.2.0: The querystring API is considered Legacy. new code should use the URLSearc
hParams API instead.
warning nuxt > @nuxt/webpack > webpack > watchpack > watchpack-chokidar2 > choki
dar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x le
ss dependencies.
warning nuxt > @nuxt/webpack > webpack > watchpack > watchpack-chokidar2 > choki
dar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using ins
ecure binaries. Upgrade to fsevents 2.
warning nuxt > @nuxt/webpack > webpack > micromatch > snapdragon > source-map-re
solve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning nuxt > @nuxt/webpack > webpack > micromatch > snapdragon > source-map-re
solve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning vue-jest > extract-from-css > css > urix@0.1.0: Please see https://githu
b.com/lydell/urix#deprecated
warning vue-jest > babel-plugin-transform-es2015-modules-commonjs > babel-runtim
e > core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for
 usage due to the number of issues. Because of the V8 engine whims, feature dete
ction in old core-js versions could cause a slowdown up to 100x even if nothing 
is polyfilled. Please, upgrade your dependencies to the actual version of core-j
s.
error babel-jest@27.0.6: The engine "node" is incompatible with this module. Exp
ected version "^10.13.0 || ^12.13.0 || ^14.15.0 || >=15.0.0". Got "14.4.0"
error Found incompatible module.

yarn install v1.22.5
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. 
Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check.
 Excluding it from installation.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this 
command.

/home/begueradj/.config/yarn/global/node_modules/sao/lib/installPackages.js:108
        throw new SAOError(`Failed to install ${packageName} in ${cwd}`)
        ^

SAOError: Failed to install packages in /home/begueradj/Development/Nuxt/nv2
    at ChildProcess.<anonymous> (/home/begueradj/.config/yarn/global/node_modules/sao/lib/installPackages.js:108:15)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1051:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5) {
  __sao: true
}
error Command failed.
Exit code: 1
Command: /home/begueradj/.yarn/bin/create-nuxt-app
Arguments: nv2
Directory: /home/begueradj/Development/Nuxt
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.

```

How to fix this ?

Billal Begueradj

**Comment by begueradj** [comment]
I had to upgrade my Node version. (feedback from stackoverflow)
